#!/usr/bin/env bash
#Install nginx web server

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" > /var/www/html/index.html
