#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the
#string Ceci n'est pas une page..

apt-get update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i "/redirect_me/ a\\\terror_page 404 /my_404.html;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/my_404.html
