#!/usr/bin/env bash
#configure web-02 to be identical to web-01

apt-get update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sed -i "/listen 80 default_server/ a\ \tadd_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server/ a\ \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "/redirect_me/ a\ \terror_page 404 /my_404.html;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/my_404.html
service nginx restart
