#!/usr/bin/env bash
#A script that generates a MySQL dump and creates a compressed archive.
sudo mysqldump -u root -p"$1" --all-databases > backup.sql
sudo tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
