#!/usr/bin/env bash
#Script to configure a server to run Nginx and have it listen on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
