#!/usr/bin/env bash
#Script to configure a server to run Nginx and have it listen on port 80

sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sed -i 's/8080/80/g' /etc/nginx/sites-available/default
service nginx restart
