#!/usr/bin/env bash
#Using what you did for task #0, make your fix short and sweet.
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
sed -i 's|pid /run/nginx.pid|pid /run/nginx_pid|' /etc/nginx/nginx.conf
