#!/usr/bin/env bash
# This script creates a file, and displays various messages depending on
#+ the signal recieved

terminate()
{
	rm /var/run/myscript.pid
	exit
}

echo $$ > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!" && exit' SIGINT
    trap 'echo "I hate the kill command" && terminate' SIGTERM
    trap 'terminate' SIGQUIT
done
