#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd;
#+ Only displays username, user id, and home directory path for the user

while read -r passwd; do
    echo "$passwd" | cut -d ':' -f1,3,6
    done < "/etc/passwd"
