#!/usr/bin/env bash
# This script displays the content of the current working directory
#+ in a list format where only the part of the name after the first dash is
#+ displayed using a for loop.
# Does not display hidden files.

list=$(ls)

for i in $list; do
   echo "$i" | cut -d '-' -f2
done
