#!/usr/bin/env bash
#A script that configures a container as #1 with shorter lines
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
